version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "FarukhSaifi"
    # Auto-merge minor and patch updates
    auto-merge:
      - match:
          dependency-type: "all"
          update-types:
            - "minor"
            - "patch"
